# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheableParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredHosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredUris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=16)),
                ('domain_name', models.CharField(max_length=255)),
                ('geo_location', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedUri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=1024)),
                ('visit_count', models.IntegerField(default=0)),
                ('should_crawl', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('referer_url', models.CharField(max_length=255)),
                ('doc_page', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(max_length=64)),
                ('browser', models.CharField(max_length=64)),
                ('device_type', models.CharField(choices=[('C', 'Computers'), ('P', 'Phones'), ('T', 'Tablets')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='referer',
            name='internal_uri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apache_monitor.RequestedUri'),
        ),
        migrations.AddField(
            model_name='referer',
            name='search_engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apache_monitor.SearchEngine'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='referer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apache_monitor.Referer'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='remote_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apache_monitor.RemoteHost'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='requested_uri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apache_monitor.RequestedUri'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='user_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apache_monitor.UserAgent'),
        ),
        migrations.AddField(
            model_name='ignoredhosts',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apache_monitor.RemoteHost'),
        ),
    ]
