# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apache_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CacheableParams',
            new_name='CacheableParam',
        ),
        migrations.RenameModel(
            old_name='IgnoredHosts',
            new_name='IgnoredHost',
        ),
        migrations.RenameModel(
            old_name='IgnoredUris',
            new_name='IgnoredUri',
        ),
    ]
