# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apache_monitor', '0002_auto_20161222_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='method',
            field=models.CharField(default='GET', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
