# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apache_monitor', '0003_auto_20161223_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referer',
            name='search_engine',
        ),
        migrations.AddField(
            model_name='useragent',
            name='search_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apache_monitor.SearchEngine'),
        ),
        migrations.AlterField(
            model_name='remotehost',
            name='domain_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='remotehost',
            name='geo_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remotehost',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useragent',
            name='device_type',
            field=models.CharField(blank=True, choices=[('C', 'Computers'), ('P', 'Phones'), ('T', 'Tablets')], max_length=1, null=True),
        ),
    ]
