# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apache_monitor', '0004_auto_20161223_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referer',
            name='url',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='remotehost',
            name='ip_address',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='requesteduri',
            name='uri',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
